arch:
- amd64
- armhf
- armv7
description: haishanh/yacd
host_network: true
image: haishanh/yacd
ingress: true
ingress_port: 80
ingress_stream: true
init: false
map:
- ssl
name: x-ui
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_icon: mdi:alpha-x
ports:
  80/tcp: null
slug: yacd
startup: services
version: latest
