---
version: 0.9.1
slug: zwave
name: OpenZWave
description: Control a ZWave network with Home Assistant
url: https://github.com/home-assistant/addons/tree/master/zwave
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
discovery:
  - ozw
homeassistant: 0.110.0.dev
image: homeassistant/{arch}-addon-zwave
ingress: true
ingress_entry: vnc_lite.html
init: false
options:
  device: null
  network_key: ""
panel_icon: mdi:z-wave
panel_title: OpenZWave
ports:
  1983/tcp: null
  5900/tcp: null
schema:
  device: device(subsystem=tty)
  instance: int(1,)?
  network_key: password
services:
  - mqtt:want
stage: deprecated
startup: services
