---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ADA_VERSION: 0.8.1
