version: '3.1'

services:
  api:
    build: .
    ports:
      - "127.0.0.1:3700:3700"
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
      - external

  external:
    build: ./external
    volumes:
      - ./config.toml:/config.toml
