---
version: 3.0.0
slug: almond
name: Genie
description: The open-source, privacy-preserving voice assistant
url: https://github.com/home-assistant/addons/blob/master/almond
arch:
  - armv7
  - aarch64
  - amd64
audio: true
discovery:
  - almond
homeassistant: 0.102.0
homeassistant_api: true
image: homeassistant/{arch}-addon-almond
ingress: true
init: false
panel_icon: mdi:comment-eye-outline
