---
version: 99.0.5
slug: homematic
name: HomeMatic CCU
description: HomeMatic central based on OCCU
url: https://github.com/home-assistant/addons/tree/master/homematic
apparmor: false
arch:
  - armv7
  - i386
gpio: true
image: homeassistant/{arch}-addon-homematic
ingress: true
map:
  - share:rw
options:
  hmip_enable: false
  hmip: []
  rf_enable: false
  rf: []
  wired_enable: false
  wired: []
panel_icon: mdi:router-wireless
panel_title: HomeMatic
ports:
  2000/tcp: null
  2001/tcp: null
  2010/tcp: null
  80/tcp: null
schema:
  hmip_enable: bool
  hmip:
    - device: device
      type: match(HMIP_CCU2)
  regahss_reset: bool?
  rf_enable: bool
  rf:
    - device: device
      reset: bool?
      type: match(CCU2)
  wired_enable: bool
  wired:
    - ip: str
      key: str
      serial: str
stage: deprecated
startup: system
timeout: 15
init: false
