 # This is a basic workflow to help you get started with Actions

name: all-in-one

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]
  schedule:
    - cron: '40 0/2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: pull
        run : |
          git clone https://github.com/alexbelgium/hassio-addons.git
          cd ./hassio-addons
          rm -r ./.github
          rm -r ./.templates
          rm -r ./.vscode
          rm ./.gitconfig
          rm ./.gitignore
          rm ./.hadolint.yaml
          rm ./.jscpd.json
          rm ./.markdownlint.yaml
          rm ./.shellcheckrc
          rm ./CODE_OF_CONDUCT.md
          rm ./CONTRIBUTING.md
          rm ./README.md
          rm ./SECURITY.md
          rm ./Stats
          rm ./repository.json
          rm ./Stats2
          cd -
          cp -r ./hassio-addons/* ./
          rm -r ./hassio-addons
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
          
      - name: pull2
        run : |
          git clone https://github.com/zigbee2mqtt/hassio-zigbee2mqtt.git
          ls 
          cd ./hassio-zigbee2mqtt
          ls
          rm -r ./.github
          rm -r ./common
          rm ./.gitignore
          rm ./CONTRIBUTING.md
          rm ./README.md
          rm ./repository.json
          cd -
          touch ./1
          cp -r ./hassio-zigbee2mqtt/* ./
          rm -r ./hassio-zigbee2mqtt
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From zigbee2mqtt/hassio-zigbee2mqtt" -a
      - name: pull3
        run : |
          git clone https://github.com/blakeblackshear/frigate-hass-addons.git
          ls 
          cd ./frigate-hass-addons
          ls
          rm -r ./.vscode
          rm ./.git-blame-ignore
          rm ./README.md
          rm ./repository.yaml
          cd -
          rm ./1
          cp -r ./frigate-hass-addons/* ./
          rm -r ./frigate-hass-addons
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From blakeblackshear/frigate-hass-addons" -a
      - name: pull
        run : |
          git clone https://github.com/devova/hassio-frp-addons.git
          cd ./hassio-frp-addons
          rm ./.DS_Store
          rm ./repository.json
          cd -
          touch ./1
          cp -r ./hassio-frp-addons/* ./
          rm -r ./hassio-frp-addons
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From devova/hassio-frp-addons" -a
      - name: pull
        run : |
          git clone https://github.com/Limych/hassio-addons.git
          cd ./hassio-addons
          rm -r ./.github
          rm ./.gitignore
          rm ./.README.j2
          rm ./.editorconfig
          rm ./.hassio-addons.yml
          rm ./LICENSE
          rm ./editorconfig.txt
          rm ./README.md
          rm ./repository.json
          cd -
          cp -r ./hassio-addons/* ./
          rm -r ./hassio-addons
          rm ./1
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
      - name: pull
        run : |
          git clone https://github.com/mKeRix/hassio-repo.git
          cd ./hassio-repo
          rm -r ./.github
          rm -r ./.devcontainer
          rm -r ./.vscode
          rm ./.editorconfig
          rm ./.gitignore
          rm ./README.md
          rm ./repository.json
          cd -
          cp -r ./hassio-repo/* ./
          rm -r ./hassio-repo
          touch ./1
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
      - name: pull
        run : |
          git clone https://github.com/esphome/home-assistant-addon.git
          cd ./home-assistant-addon
          rm -r ./.github
          rm -r ./.devcontainer
          rm -r ./.vscode
          rm -r ./script
          rm -r ./template
          rm ./repository.json
          rm ./README.md
          rm ./.gitignore
          cd -
          cp -r ./home-assistant-addon/* ./
          rm -r ./home-assistant-addon
          rm ./1
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
      - name: pull
        run : |
          git clone https://github.com/home-assistant/addons.git
          cd ./addons
          rm -r ./.github
          rm -r ./.devcontainer
          rm -r ./.vscode
          rm -r ./.hadolint.yaml
          rm -r ./LICENSE
          rm ./README.md
          cd -
          cp -r ./addons/* ./
          rm -r ./addons
          touch ./1
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
          
      - name: pull
        run : |
          git clone https://github.com/hassio-addons/repository-beta.git
          cd ./repository-beta
          rm -r ./.github
          rm  ./.README.j2
          rm  ./.addons.yml
          rm ./.gitignore
          rm ./.mdlrc
          rm ./.yamllint
          rm ./LICENSE.md
          rm ./README.md
          rm ./repository.json
          cd -
          cp -r ./repository-beta/* ./
          rm -r ./repository-beta
          rm ./1
          git config --global user.email yzr@yserver.top
          git config --global user.name y
          git add .
          git commit -m "From alexbelgium/hassio-addons" 
#      - name: commit
#        run: |
#          git config --global user.email 3196@qq.com
#          git config --global user.name ndt
#          git add .
#          git commit -m "update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
